name = "oryx"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
compatibility_date = "2022-02-15"
kv_namespaces = [ 
    { binding = "ORYX", id = "" }
]